// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	internal "github.com/openshift/client-go/update/applyconfigurations/internal"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=update.openshift.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterOperatorProgressInsight"):
		return &updatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterOperatorProgressInsightStatus"):
		return &updatev1alpha1.ClusterOperatorProgressInsightStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterVersionProgressInsight"):
		return &updatev1alpha1.ClusterVersionProgressInsightApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterVersionProgressInsightStatus"):
		return &updatev1alpha1.ClusterVersionProgressInsightStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ControlPlaneUpdateVersions"):
		return &updatev1alpha1.ControlPlaneUpdateVersionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HealthInsight"):
		return &updatev1alpha1.HealthInsightApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HealthInsightStatus"):
		return &updatev1alpha1.HealthInsightStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InsightImpact"):
		return &updatev1alpha1.InsightImpactApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InsightRemediation"):
		return &updatev1alpha1.InsightRemediationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("InsightScope"):
		return &updatev1alpha1.InsightScopeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineConfigPoolProgressInsight"):
		return &updatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("MachineConfigPoolProgressInsightStatus"):
		return &updatev1alpha1.MachineConfigPoolProgressInsightStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodeProgressInsight"):
		return &updatev1alpha1.NodeProgressInsightApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodeProgressInsightStatus"):
		return &updatev1alpha1.NodeProgressInsightStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NodeSummary"):
		return &updatev1alpha1.NodeSummaryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ResourceRef"):
		return &updatev1alpha1.ResourceRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Version"):
		return &updatev1alpha1.VersionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("VersionMetadata"):
		return &updatev1alpha1.VersionMetadataApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) *testing.TypeConverter {
	return &testing.TypeConverter{Scheme: scheme, TypeResolver: internal.Parser()}
}
