// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	typedupdatev1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterOperatorProgressInsights implements ClusterOperatorProgressInsightInterface
type fakeClusterOperatorProgressInsights struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterOperatorProgressInsight, *v1alpha1.ClusterOperatorProgressInsightList, *updatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration]
	Fake *FakeUpdateV1alpha1
}

func newFakeClusterOperatorProgressInsights(fake *FakeUpdateV1alpha1) typedupdatev1alpha1.ClusterOperatorProgressInsightInterface {
	return &fakeClusterOperatorProgressInsights{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterOperatorProgressInsight, *v1alpha1.ClusterOperatorProgressInsightList, *updatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusteroperatorprogressinsights"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterOperatorProgressInsight"),
			func() *v1alpha1.ClusterOperatorProgressInsight { return &v1alpha1.ClusterOperatorProgressInsight{} },
			func() *v1alpha1.ClusterOperatorProgressInsightList {
				return &v1alpha1.ClusterOperatorProgressInsightList{}
			},
			func(dst, src *v1alpha1.ClusterOperatorProgressInsightList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterOperatorProgressInsightList) []*v1alpha1.ClusterOperatorProgressInsight {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterOperatorProgressInsightList, items []*v1alpha1.ClusterOperatorProgressInsight) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
