// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	typedupdatev1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodeProgressInsights implements NodeProgressInsightInterface
type fakeNodeProgressInsights struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.NodeProgressInsight, *v1alpha1.NodeProgressInsightList, *updatev1alpha1.NodeProgressInsightApplyConfiguration]
	Fake *FakeUpdateV1alpha1
}

func newFakeNodeProgressInsights(fake *FakeUpdateV1alpha1) typedupdatev1alpha1.NodeProgressInsightInterface {
	return &fakeNodeProgressInsights{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.NodeProgressInsight, *v1alpha1.NodeProgressInsightList, *updatev1alpha1.NodeProgressInsightApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("nodeprogressinsights"),
			v1alpha1.SchemeGroupVersion.WithKind("NodeProgressInsight"),
			func() *v1alpha1.NodeProgressInsight { return &v1alpha1.NodeProgressInsight{} },
			func() *v1alpha1.NodeProgressInsightList { return &v1alpha1.NodeProgressInsightList{} },
			func(dst, src *v1alpha1.NodeProgressInsightList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.NodeProgressInsightList) []*v1alpha1.NodeProgressInsight {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.NodeProgressInsightList, items []*v1alpha1.NodeProgressInsight) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
