// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	typedupdatev1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHealthInsights implements HealthInsightInterface
type fakeHealthInsights struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.HealthInsight, *v1alpha1.HealthInsightList, *updatev1alpha1.HealthInsightApplyConfiguration]
	Fake *FakeUpdateV1alpha1
}

func newFakeHealthInsights(fake *FakeUpdateV1alpha1) typedupdatev1alpha1.HealthInsightInterface {
	return &fakeHealthInsights{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.HealthInsight, *v1alpha1.HealthInsightList, *updatev1alpha1.HealthInsightApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("healthinsights"),
			v1alpha1.SchemeGroupVersion.WithKind("HealthInsight"),
			func() *v1alpha1.HealthInsight { return &v1alpha1.HealthInsight{} },
			func() *v1alpha1.HealthInsightList { return &v1alpha1.HealthInsightList{} },
			func(dst, src *v1alpha1.HealthInsightList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.HealthInsightList) []*v1alpha1.HealthInsight {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.HealthInsightList, items []*v1alpha1.HealthInsight) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
