// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	typedupdatev1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterVersionProgressInsights implements ClusterVersionProgressInsightInterface
type fakeClusterVersionProgressInsights struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ClusterVersionProgressInsight, *v1alpha1.ClusterVersionProgressInsightList, *updatev1alpha1.ClusterVersionProgressInsightApplyConfiguration]
	Fake *FakeUpdateV1alpha1
}

func newFakeClusterVersionProgressInsights(fake *FakeUpdateV1alpha1) typedupdatev1alpha1.ClusterVersionProgressInsightInterface {
	return &fakeClusterVersionProgressInsights{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ClusterVersionProgressInsight, *v1alpha1.ClusterVersionProgressInsightList, *updatev1alpha1.ClusterVersionProgressInsightApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("clusterversionprogressinsights"),
			v1alpha1.SchemeGroupVersion.WithKind("ClusterVersionProgressInsight"),
			func() *v1alpha1.ClusterVersionProgressInsight { return &v1alpha1.ClusterVersionProgressInsight{} },
			func() *v1alpha1.ClusterVersionProgressInsightList {
				return &v1alpha1.ClusterVersionProgressInsightList{}
			},
			func(dst, src *v1alpha1.ClusterVersionProgressInsightList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClusterVersionProgressInsightList) []*v1alpha1.ClusterVersionProgressInsight {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClusterVersionProgressInsightList, items []*v1alpha1.ClusterVersionProgressInsight) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
