// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/api/update/v1alpha1"
	updatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	typedupdatev1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMachineConfigPoolProgressInsights implements MachineConfigPoolProgressInsightInterface
type fakeMachineConfigPoolProgressInsights struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.MachineConfigPoolProgressInsight, *v1alpha1.MachineConfigPoolProgressInsightList, *updatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration]
	Fake *FakeUpdateV1alpha1
}

func newFakeMachineConfigPoolProgressInsights(fake *FakeUpdateV1alpha1) typedupdatev1alpha1.MachineConfigPoolProgressInsightInterface {
	return &fakeMachineConfigPoolProgressInsights{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.MachineConfigPoolProgressInsight, *v1alpha1.MachineConfigPoolProgressInsightList, *updatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("machineconfigpoolprogressinsights"),
			v1alpha1.SchemeGroupVersion.WithKind("MachineConfigPoolProgressInsight"),
			func() *v1alpha1.MachineConfigPoolProgressInsight { return &v1alpha1.MachineConfigPoolProgressInsight{} },
			func() *v1alpha1.MachineConfigPoolProgressInsightList {
				return &v1alpha1.MachineConfigPoolProgressInsightList{}
			},
			func(dst, src *v1alpha1.MachineConfigPoolProgressInsightList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MachineConfigPoolProgressInsightList) []*v1alpha1.MachineConfigPoolProgressInsight {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.MachineConfigPoolProgressInsightList, items []*v1alpha1.MachineConfigPoolProgressInsight) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
