// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/client-go/update/clientset/versioned/typed/update/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeUpdateV1alpha1 struct {
	*testing.Fake
}

func (c *FakeUpdateV1alpha1) ClusterOperatorProgressInsights() v1alpha1.ClusterOperatorProgressInsightInterface {
	return newFakeClusterOperatorProgressInsights(c)
}

func (c *FakeUpdateV1alpha1) ClusterVersionProgressInsights() v1alpha1.ClusterVersionProgressInsightInterface {
	return newFakeClusterVersionProgressInsights(c)
}

func (c *FakeUpdateV1alpha1) HealthInsights() v1alpha1.HealthInsightInterface {
	return newFakeHealthInsights(c)
}

func (c *FakeUpdateV1alpha1) MachineConfigPoolProgressInsights() v1alpha1.MachineConfigPoolProgressInsightInterface {
	return newFakeMachineConfigPoolProgressInsights(c)
}

func (c *FakeUpdateV1alpha1) NodeProgressInsights() v1alpha1.NodeProgressInsightInterface {
	return newFakeNodeProgressInsights(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeUpdateV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
