// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	internal "github.com/openshift/client-go/update/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterOperatorProgressInsightApplyConfiguration represents a declarative configuration of the ClusterOperatorProgressInsight type for use
// with apply.
type ClusterOperatorProgressInsightApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *updatev1alpha1.ClusterOperatorProgressInsightSpec      `json:"spec,omitempty"`
	Status                           *ClusterOperatorProgressInsightStatusApplyConfiguration `json:"status,omitempty"`
}

// ClusterOperatorProgressInsight constructs a declarative configuration of the ClusterOperatorProgressInsight type for use with
// apply.
func ClusterOperatorProgressInsight(name string) *ClusterOperatorProgressInsightApplyConfiguration {
	b := &ClusterOperatorProgressInsightApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ClusterOperatorProgressInsight")
	b.WithAPIVersion("update.openshift.io/v1alpha1")
	return b
}

// ExtractClusterOperatorProgressInsight extracts the applied configuration owned by fieldManager from
// clusterOperatorProgressInsight. If no managedFields are found in clusterOperatorProgressInsight for fieldManager, a
// ClusterOperatorProgressInsightApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// clusterOperatorProgressInsight must be a unmodified ClusterOperatorProgressInsight API object that was retrieved from the Kubernetes API.
// ExtractClusterOperatorProgressInsight provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
// Experimental!
func ExtractClusterOperatorProgressInsight(clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, fieldManager string) (*ClusterOperatorProgressInsightApplyConfiguration, error) {
	return extractClusterOperatorProgressInsight(clusterOperatorProgressInsight, fieldManager, "")
}

// ExtractClusterOperatorProgressInsightStatus is the same as ExtractClusterOperatorProgressInsight except
// that it extracts the status subresource applied configuration.
// Experimental!
func ExtractClusterOperatorProgressInsightStatus(clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, fieldManager string) (*ClusterOperatorProgressInsightApplyConfiguration, error) {
	return extractClusterOperatorProgressInsight(clusterOperatorProgressInsight, fieldManager, "status")
}

func extractClusterOperatorProgressInsight(clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, fieldManager string, subresource string) (*ClusterOperatorProgressInsightApplyConfiguration, error) {
	b := &ClusterOperatorProgressInsightApplyConfiguration{}
	err := managedfields.ExtractInto(clusterOperatorProgressInsight, internal.Parser().Type("com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsight"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(clusterOperatorProgressInsight.Name)

	b.WithKind("ClusterOperatorProgressInsight")
	b.WithAPIVersion("update.openshift.io/v1alpha1")
	return b, nil
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithKind(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithAPIVersion(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithName(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithGenerateName(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithNamespace(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithUID(value types.UID) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithResourceVersion(value string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithGeneration(value int64) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithCreationTimestamp(value metav1.Time) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithLabels(entries map[string]string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithAnnotations(entries map[string]string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithFinalizers(values ...string) *ClusterOperatorProgressInsightApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ClusterOperatorProgressInsightApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithSpec(value updatev1alpha1.ClusterOperatorProgressInsightSpec) *ClusterOperatorProgressInsightApplyConfiguration {
	b.Spec = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightApplyConfiguration) WithStatus(value *ClusterOperatorProgressInsightStatusApplyConfiguration) *ClusterOperatorProgressInsightApplyConfiguration {
	b.Status = value
	return b
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ClusterOperatorProgressInsightApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}
