// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterOperatorProgressInsightStatusApplyConfiguration represents a declarative configuration of the ClusterOperatorProgressInsightStatus type for use
// with apply.
type ClusterOperatorProgressInsightStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Name       *string                          `json:"name,omitempty"`
}

// ClusterOperatorProgressInsightStatusApplyConfiguration constructs a declarative configuration of the ClusterOperatorProgressInsightStatus type for use with
// apply.
func ClusterOperatorProgressInsightStatus() *ClusterOperatorProgressInsightStatusApplyConfiguration {
	return &ClusterOperatorProgressInsightStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterOperatorProgressInsightStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterOperatorProgressInsightStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterOperatorProgressInsightStatusApplyConfiguration) WithName(value string) *ClusterOperatorProgressInsightStatusApplyConfiguration {
	b.Name = &value
	return b
}
