// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// HealthInsightStatusApplyConfiguration represents a declarative configuration of the HealthInsightStatus type for use
// with apply.
type HealthInsightStatusApplyConfiguration struct {
	StartedAt   *v1.Time                              `json:"startedAt,omitempty"`
	Scope       *InsightScopeApplyConfiguration       `json:"scope,omitempty"`
	Impact      *InsightImpactApplyConfiguration      `json:"impact,omitempty"`
	Remediation *InsightRemediationApplyConfiguration `json:"remediation,omitempty"`
}

// HealthInsightStatusApplyConfiguration constructs a declarative configuration of the HealthInsightStatus type for use with
// apply.
func HealthInsightStatus() *HealthInsightStatusApplyConfiguration {
	return &HealthInsightStatusApplyConfiguration{}
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *HealthInsightStatusApplyConfiguration) WithStartedAt(value v1.Time) *HealthInsightStatusApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *HealthInsightStatusApplyConfiguration) WithScope(value *InsightScopeApplyConfiguration) *HealthInsightStatusApplyConfiguration {
	b.Scope = value
	return b
}

// WithImpact sets the Impact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Impact field is set to the value of the last call.
func (b *HealthInsightStatusApplyConfiguration) WithImpact(value *InsightImpactApplyConfiguration) *HealthInsightStatusApplyConfiguration {
	b.Impact = value
	return b
}

// WithRemediation sets the Remediation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remediation field is set to the value of the last call.
func (b *HealthInsightStatusApplyConfiguration) WithRemediation(value *InsightRemediationApplyConfiguration) *HealthInsightStatusApplyConfiguration {
	b.Remediation = value
	return b
}
