// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MachineConfigPoolProgressInsightStatusApplyConfiguration represents a declarative configuration of the MachineConfigPoolProgressInsightStatus type for use
// with apply.
type MachineConfigPoolProgressInsightStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Name       *string                          `json:"name,omitempty"`
	Scope      *updatev1alpha1.ScopeType        `json:"scopeType,omitempty"`
	Assessment *updatev1alpha1.PoolAssessment   `json:"assessment,omitempty"`
	Completion *int32                           `json:"completionPercent,omitempty"`
	Summaries  []NodeSummaryApplyConfiguration  `json:"summaries,omitempty"`
}

// MachineConfigPoolProgressInsightStatusApplyConfiguration constructs a declarative configuration of the MachineConfigPoolProgressInsightStatus type for use with
// apply.
func MachineConfigPoolProgressInsightStatus() *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	return &MachineConfigPoolProgressInsightStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithName(value string) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithScope(value updatev1alpha1.ScopeType) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	b.Scope = &value
	return b
}

// WithAssessment sets the Assessment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Assessment field is set to the value of the last call.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithAssessment(value updatev1alpha1.PoolAssessment) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	b.Assessment = &value
	return b
}

// WithCompletion sets the Completion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Completion field is set to the value of the last call.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithCompletion(value int32) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	b.Completion = &value
	return b
}

// WithSummaries adds the given value to the Summaries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Summaries field.
func (b *MachineConfigPoolProgressInsightStatusApplyConfiguration) WithSummaries(values ...*NodeSummaryApplyConfiguration) *MachineConfigPoolProgressInsightStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSummaries")
		}
		b.Summaries = append(b.Summaries, *values[i])
	}
	return b
}
