// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NodeProgressInsightStatusApplyConfiguration represents a declarative configuration of the NodeProgressInsightStatus type for use
// with apply.
type NodeProgressInsightStatusApplyConfiguration struct {
	Conditions          []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Name                *string                          `json:"name,omitempty"`
	PoolResource        *ResourceRefApplyConfiguration   `json:"poolResource,omitempty"`
	Scope               *updatev1alpha1.ScopeType        `json:"scopeType,omitempty"`
	Version             *string                          `json:"version,omitempty"`
	EstimatedToComplete *metav1.Duration                 `json:"estimatedToComplete,omitempty"`
	Message             *string                          `json:"message,omitempty"`
}

// NodeProgressInsightStatusApplyConfiguration constructs a declarative configuration of the NodeProgressInsightStatus type for use with
// apply.
func NodeProgressInsightStatus() *NodeProgressInsightStatusApplyConfiguration {
	return &NodeProgressInsightStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *NodeProgressInsightStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *NodeProgressInsightStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithName(value string) *NodeProgressInsightStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithPoolResource sets the PoolResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolResource field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithPoolResource(value *ResourceRefApplyConfiguration) *NodeProgressInsightStatusApplyConfiguration {
	b.PoolResource = value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithScope(value updatev1alpha1.ScopeType) *NodeProgressInsightStatusApplyConfiguration {
	b.Scope = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithVersion(value string) *NodeProgressInsightStatusApplyConfiguration {
	b.Version = &value
	return b
}

// WithEstimatedToComplete sets the EstimatedToComplete field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EstimatedToComplete field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithEstimatedToComplete(value metav1.Duration) *NodeProgressInsightStatusApplyConfiguration {
	b.EstimatedToComplete = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *NodeProgressInsightStatusApplyConfiguration) WithMessage(value string) *NodeProgressInsightStatusApplyConfiguration {
	b.Message = &value
	return b
}
