// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiupdatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	versioned "github.com/openshift/client-go/update/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/update/informers/externalversions/internalinterfaces"
	updatev1alpha1 "github.com/openshift/client-go/update/listers/update/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HealthInsightInformer provides access to a shared informer and lister for
// HealthInsights.
type HealthInsightInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() updatev1alpha1.HealthInsightLister
}

type healthInsightInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHealthInsightInformer constructs a new informer for HealthInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHealthInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHealthInsightInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHealthInsightInformer constructs a new informer for HealthInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHealthInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().HealthInsights().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().HealthInsights().Watch(context.TODO(), options)
			},
		},
		&apiupdatev1alpha1.HealthInsight{},
		resyncPeriod,
		indexers,
	)
}

func (f *healthInsightInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHealthInsightInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *healthInsightInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiupdatev1alpha1.HealthInsight{}, f.defaultInformer)
}

func (f *healthInsightInformer) Lister() updatev1alpha1.HealthInsightLister {
	return updatev1alpha1.NewHealthInsightLister(f.Informer().GetIndexer())
}
