// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/openshift/client-go/update/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterOperatorProgressInsights returns a ClusterOperatorProgressInsightInformer.
	ClusterOperatorProgressInsights() ClusterOperatorProgressInsightInformer
	// ClusterVersionProgressInsights returns a ClusterVersionProgressInsightInformer.
	ClusterVersionProgressInsights() ClusterVersionProgressInsightInformer
	// HealthInsights returns a HealthInsightInformer.
	HealthInsights() HealthInsightInformer
	// MachineConfigPoolProgressInsights returns a MachineConfigPoolProgressInsightInformer.
	MachineConfigPoolProgressInsights() MachineConfigPoolProgressInsightInformer
	// NodeProgressInsights returns a NodeProgressInsightInformer.
	NodeProgressInsights() NodeProgressInsightInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterOperatorProgressInsights returns a ClusterOperatorProgressInsightInformer.
func (v *version) ClusterOperatorProgressInsights() ClusterOperatorProgressInsightInformer {
	return &clusterOperatorProgressInsightInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ClusterVersionProgressInsights returns a ClusterVersionProgressInsightInformer.
func (v *version) ClusterVersionProgressInsights() ClusterVersionProgressInsightInformer {
	return &clusterVersionProgressInsightInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// HealthInsights returns a HealthInsightInformer.
func (v *version) HealthInsights() HealthInsightInformer {
	return &healthInsightInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// MachineConfigPoolProgressInsights returns a MachineConfigPoolProgressInsightInformer.
func (v *version) MachineConfigPoolProgressInsights() MachineConfigPoolProgressInsightInformer {
	return &machineConfigPoolProgressInsightInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// NodeProgressInsights returns a NodeProgressInsightInformer.
func (v *version) NodeProgressInsights() NodeProgressInsightInformer {
	return &nodeProgressInsightInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
