// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiupdatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	versioned "github.com/openshift/client-go/update/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/update/informers/externalversions/internalinterfaces"
	updatev1alpha1 "github.com/openshift/client-go/update/listers/update/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MachineConfigPoolProgressInsightInformer provides access to a shared informer and lister for
// MachineConfigPoolProgressInsights.
type MachineConfigPoolProgressInsightInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() updatev1alpha1.MachineConfigPoolProgressInsightLister
}

type machineConfigPoolProgressInsightInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMachineConfigPoolProgressInsightInformer constructs a new informer for MachineConfigPoolProgressInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMachineConfigPoolProgressInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMachineConfigPoolProgressInsightInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMachineConfigPoolProgressInsightInformer constructs a new informer for MachineConfigPoolProgressInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMachineConfigPoolProgressInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().MachineConfigPoolProgressInsights().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().MachineConfigPoolProgressInsights().Watch(context.TODO(), options)
			},
		},
		&apiupdatev1alpha1.MachineConfigPoolProgressInsight{},
		resyncPeriod,
		indexers,
	)
}

func (f *machineConfigPoolProgressInsightInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMachineConfigPoolProgressInsightInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *machineConfigPoolProgressInsightInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiupdatev1alpha1.MachineConfigPoolProgressInsight{}, f.defaultInformer)
}

func (f *machineConfigPoolProgressInsightInformer) Lister() updatev1alpha1.MachineConfigPoolProgressInsightLister {
	return updatev1alpha1.NewMachineConfigPoolProgressInsightLister(f.Informer().GetIndexer())
}
