// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiupdatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	versioned "github.com/openshift/client-go/update/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/update/informers/externalversions/internalinterfaces"
	updatev1alpha1 "github.com/openshift/client-go/update/listers/update/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodeProgressInsightInformer provides access to a shared informer and lister for
// NodeProgressInsights.
type NodeProgressInsightInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() updatev1alpha1.NodeProgressInsightLister
}

type nodeProgressInsightInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNodeProgressInsightInformer constructs a new informer for NodeProgressInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeProgressInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeProgressInsightInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNodeProgressInsightInformer constructs a new informer for NodeProgressInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeProgressInsightInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().NodeProgressInsights().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UpdateV1alpha1().NodeProgressInsights().Watch(context.TODO(), options)
			},
		},
		&apiupdatev1alpha1.NodeProgressInsight{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeProgressInsightInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeProgressInsightInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeProgressInsightInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiupdatev1alpha1.NodeProgressInsight{}, f.defaultInformer)
}

func (f *nodeProgressInsightInformer) Lister() updatev1alpha1.NodeProgressInsightLister {
	return updatev1alpha1.NewNodeProgressInsightLister(f.Informer().GetIndexer())
}
