// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	applyconfigurationsupdatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	scheme "github.com/openshift/client-go/update/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterVersionProgressInsightsGetter has a method to return a ClusterVersionProgressInsightInterface.
// A group's client should implement this interface.
type ClusterVersionProgressInsightsGetter interface {
	ClusterVersionProgressInsights() ClusterVersionProgressInsightInterface
}

// ClusterVersionProgressInsightInterface has methods to work with ClusterVersionProgressInsight resources.
type ClusterVersionProgressInsightInterface interface {
	Create(ctx context.Context, clusterVersionProgressInsight *updatev1alpha1.ClusterVersionProgressInsight, opts v1.CreateOptions) (*updatev1alpha1.ClusterVersionProgressInsight, error)
	Update(ctx context.Context, clusterVersionProgressInsight *updatev1alpha1.ClusterVersionProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.ClusterVersionProgressInsight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterVersionProgressInsight *updatev1alpha1.ClusterVersionProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.ClusterVersionProgressInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*updatev1alpha1.ClusterVersionProgressInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*updatev1alpha1.ClusterVersionProgressInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *updatev1alpha1.ClusterVersionProgressInsight, err error)
	Apply(ctx context.Context, clusterVersionProgressInsight *applyconfigurationsupdatev1alpha1.ClusterVersionProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.ClusterVersionProgressInsight, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterVersionProgressInsight *applyconfigurationsupdatev1alpha1.ClusterVersionProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.ClusterVersionProgressInsight, err error)
	ClusterVersionProgressInsightExpansion
}

// clusterVersionProgressInsights implements ClusterVersionProgressInsightInterface
type clusterVersionProgressInsights struct {
	*gentype.ClientWithListAndApply[*updatev1alpha1.ClusterVersionProgressInsight, *updatev1alpha1.ClusterVersionProgressInsightList, *applyconfigurationsupdatev1alpha1.ClusterVersionProgressInsightApplyConfiguration]
}

// newClusterVersionProgressInsights returns a ClusterVersionProgressInsights
func newClusterVersionProgressInsights(c *UpdateV1alpha1Client) *clusterVersionProgressInsights {
	return &clusterVersionProgressInsights{
		gentype.NewClientWithListAndApply[*updatev1alpha1.ClusterVersionProgressInsight, *updatev1alpha1.ClusterVersionProgressInsightList, *applyconfigurationsupdatev1alpha1.ClusterVersionProgressInsightApplyConfiguration](
			"clusterversionprogressinsights",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *updatev1alpha1.ClusterVersionProgressInsight {
				return &updatev1alpha1.ClusterVersionProgressInsight{}
			},
			func() *updatev1alpha1.ClusterVersionProgressInsightList {
				return &updatev1alpha1.ClusterVersionProgressInsightList{}
			},
		),
	}
}
