// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	applyconfigurationsupdatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	scheme "github.com/openshift/client-go/update/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterOperatorProgressInsightsGetter has a method to return a ClusterOperatorProgressInsightInterface.
// A group's client should implement this interface.
type ClusterOperatorProgressInsightsGetter interface {
	ClusterOperatorProgressInsights() ClusterOperatorProgressInsightInterface
}

// ClusterOperatorProgressInsightInterface has methods to work with ClusterOperatorProgressInsight resources.
type ClusterOperatorProgressInsightInterface interface {
	Create(ctx context.Context, clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, opts v1.CreateOptions) (*updatev1alpha1.ClusterOperatorProgressInsight, error)
	Update(ctx context.Context, clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.ClusterOperatorProgressInsight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterOperatorProgressInsight *updatev1alpha1.ClusterOperatorProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.ClusterOperatorProgressInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*updatev1alpha1.ClusterOperatorProgressInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*updatev1alpha1.ClusterOperatorProgressInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *updatev1alpha1.ClusterOperatorProgressInsight, err error)
	Apply(ctx context.Context, clusterOperatorProgressInsight *applyconfigurationsupdatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.ClusterOperatorProgressInsight, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterOperatorProgressInsight *applyconfigurationsupdatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.ClusterOperatorProgressInsight, err error)
	ClusterOperatorProgressInsightExpansion
}

// clusterOperatorProgressInsights implements ClusterOperatorProgressInsightInterface
type clusterOperatorProgressInsights struct {
	*gentype.ClientWithListAndApply[*updatev1alpha1.ClusterOperatorProgressInsight, *updatev1alpha1.ClusterOperatorProgressInsightList, *applyconfigurationsupdatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration]
}

// newClusterOperatorProgressInsights returns a ClusterOperatorProgressInsights
func newClusterOperatorProgressInsights(c *UpdateV1alpha1Client) *clusterOperatorProgressInsights {
	return &clusterOperatorProgressInsights{
		gentype.NewClientWithListAndApply[*updatev1alpha1.ClusterOperatorProgressInsight, *updatev1alpha1.ClusterOperatorProgressInsightList, *applyconfigurationsupdatev1alpha1.ClusterOperatorProgressInsightApplyConfiguration](
			"clusteroperatorprogressinsights",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *updatev1alpha1.ClusterOperatorProgressInsight {
				return &updatev1alpha1.ClusterOperatorProgressInsight{}
			},
			func() *updatev1alpha1.ClusterOperatorProgressInsightList {
				return &updatev1alpha1.ClusterOperatorProgressInsightList{}
			},
		),
	}
}
