// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterOperatorProgressInsightExpansion interface{}

type ClusterVersionProgressInsightExpansion interface{}

type HealthInsightExpansion interface{}

type MachineConfigPoolProgressInsightExpansion interface{}

type NodeProgressInsightExpansion interface{}
