// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	applyconfigurationsupdatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	scheme "github.com/openshift/client-go/update/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HealthInsightsGetter has a method to return a HealthInsightInterface.
// A group's client should implement this interface.
type HealthInsightsGetter interface {
	HealthInsights() HealthInsightInterface
}

// HealthInsightInterface has methods to work with HealthInsight resources.
type HealthInsightInterface interface {
	Create(ctx context.Context, healthInsight *updatev1alpha1.HealthInsight, opts v1.CreateOptions) (*updatev1alpha1.HealthInsight, error)
	Update(ctx context.Context, healthInsight *updatev1alpha1.HealthInsight, opts v1.UpdateOptions) (*updatev1alpha1.HealthInsight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, healthInsight *updatev1alpha1.HealthInsight, opts v1.UpdateOptions) (*updatev1alpha1.HealthInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*updatev1alpha1.HealthInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*updatev1alpha1.HealthInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *updatev1alpha1.HealthInsight, err error)
	Apply(ctx context.Context, healthInsight *applyconfigurationsupdatev1alpha1.HealthInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.HealthInsight, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, healthInsight *applyconfigurationsupdatev1alpha1.HealthInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.HealthInsight, err error)
	HealthInsightExpansion
}

// healthInsights implements HealthInsightInterface
type healthInsights struct {
	*gentype.ClientWithListAndApply[*updatev1alpha1.HealthInsight, *updatev1alpha1.HealthInsightList, *applyconfigurationsupdatev1alpha1.HealthInsightApplyConfiguration]
}

// newHealthInsights returns a HealthInsights
func newHealthInsights(c *UpdateV1alpha1Client) *healthInsights {
	return &healthInsights{
		gentype.NewClientWithListAndApply[*updatev1alpha1.HealthInsight, *updatev1alpha1.HealthInsightList, *applyconfigurationsupdatev1alpha1.HealthInsightApplyConfiguration](
			"healthinsights",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *updatev1alpha1.HealthInsight { return &updatev1alpha1.HealthInsight{} },
			func() *updatev1alpha1.HealthInsightList { return &updatev1alpha1.HealthInsightList{} },
		),
	}
}
