// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	applyconfigurationsupdatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	scheme "github.com/openshift/client-go/update/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MachineConfigPoolProgressInsightsGetter has a method to return a MachineConfigPoolProgressInsightInterface.
// A group's client should implement this interface.
type MachineConfigPoolProgressInsightsGetter interface {
	MachineConfigPoolProgressInsights() MachineConfigPoolProgressInsightInterface
}

// MachineConfigPoolProgressInsightInterface has methods to work with MachineConfigPoolProgressInsight resources.
type MachineConfigPoolProgressInsightInterface interface {
	Create(ctx context.Context, machineConfigPoolProgressInsight *updatev1alpha1.MachineConfigPoolProgressInsight, opts v1.CreateOptions) (*updatev1alpha1.MachineConfigPoolProgressInsight, error)
	Update(ctx context.Context, machineConfigPoolProgressInsight *updatev1alpha1.MachineConfigPoolProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.MachineConfigPoolProgressInsight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, machineConfigPoolProgressInsight *updatev1alpha1.MachineConfigPoolProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.MachineConfigPoolProgressInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*updatev1alpha1.MachineConfigPoolProgressInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*updatev1alpha1.MachineConfigPoolProgressInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *updatev1alpha1.MachineConfigPoolProgressInsight, err error)
	Apply(ctx context.Context, machineConfigPoolProgressInsight *applyconfigurationsupdatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.MachineConfigPoolProgressInsight, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, machineConfigPoolProgressInsight *applyconfigurationsupdatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.MachineConfigPoolProgressInsight, err error)
	MachineConfigPoolProgressInsightExpansion
}

// machineConfigPoolProgressInsights implements MachineConfigPoolProgressInsightInterface
type machineConfigPoolProgressInsights struct {
	*gentype.ClientWithListAndApply[*updatev1alpha1.MachineConfigPoolProgressInsight, *updatev1alpha1.MachineConfigPoolProgressInsightList, *applyconfigurationsupdatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration]
}

// newMachineConfigPoolProgressInsights returns a MachineConfigPoolProgressInsights
func newMachineConfigPoolProgressInsights(c *UpdateV1alpha1Client) *machineConfigPoolProgressInsights {
	return &machineConfigPoolProgressInsights{
		gentype.NewClientWithListAndApply[*updatev1alpha1.MachineConfigPoolProgressInsight, *updatev1alpha1.MachineConfigPoolProgressInsightList, *applyconfigurationsupdatev1alpha1.MachineConfigPoolProgressInsightApplyConfiguration](
			"machineconfigpoolprogressinsights",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *updatev1alpha1.MachineConfigPoolProgressInsight {
				return &updatev1alpha1.MachineConfigPoolProgressInsight{}
			},
			func() *updatev1alpha1.MachineConfigPoolProgressInsightList {
				return &updatev1alpha1.MachineConfigPoolProgressInsightList{}
			},
		),
	}
}
