// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	applyconfigurationsupdatev1alpha1 "github.com/openshift/client-go/update/applyconfigurations/update/v1alpha1"
	scheme "github.com/openshift/client-go/update/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodeProgressInsightsGetter has a method to return a NodeProgressInsightInterface.
// A group's client should implement this interface.
type NodeProgressInsightsGetter interface {
	NodeProgressInsights() NodeProgressInsightInterface
}

// NodeProgressInsightInterface has methods to work with NodeProgressInsight resources.
type NodeProgressInsightInterface interface {
	Create(ctx context.Context, nodeProgressInsight *updatev1alpha1.NodeProgressInsight, opts v1.CreateOptions) (*updatev1alpha1.NodeProgressInsight, error)
	Update(ctx context.Context, nodeProgressInsight *updatev1alpha1.NodeProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.NodeProgressInsight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nodeProgressInsight *updatev1alpha1.NodeProgressInsight, opts v1.UpdateOptions) (*updatev1alpha1.NodeProgressInsight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*updatev1alpha1.NodeProgressInsight, error)
	List(ctx context.Context, opts v1.ListOptions) (*updatev1alpha1.NodeProgressInsightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *updatev1alpha1.NodeProgressInsight, err error)
	Apply(ctx context.Context, nodeProgressInsight *applyconfigurationsupdatev1alpha1.NodeProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.NodeProgressInsight, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, nodeProgressInsight *applyconfigurationsupdatev1alpha1.NodeProgressInsightApplyConfiguration, opts v1.ApplyOptions) (result *updatev1alpha1.NodeProgressInsight, err error)
	NodeProgressInsightExpansion
}

// nodeProgressInsights implements NodeProgressInsightInterface
type nodeProgressInsights struct {
	*gentype.ClientWithListAndApply[*updatev1alpha1.NodeProgressInsight, *updatev1alpha1.NodeProgressInsightList, *applyconfigurationsupdatev1alpha1.NodeProgressInsightApplyConfiguration]
}

// newNodeProgressInsights returns a NodeProgressInsights
func newNodeProgressInsights(c *UpdateV1alpha1Client) *nodeProgressInsights {
	return &nodeProgressInsights{
		gentype.NewClientWithListAndApply[*updatev1alpha1.NodeProgressInsight, *updatev1alpha1.NodeProgressInsightList, *applyconfigurationsupdatev1alpha1.NodeProgressInsightApplyConfiguration](
			"nodeprogressinsights",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *updatev1alpha1.NodeProgressInsight { return &updatev1alpha1.NodeProgressInsight{} },
			func() *updatev1alpha1.NodeProgressInsightList { return &updatev1alpha1.NodeProgressInsightList{} },
		),
	}
}
