// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterOperatorProgressInsightLister helps list ClusterOperatorProgressInsights.
// All objects returned here must be treated as read-only.
type ClusterOperatorProgressInsightLister interface {
	// List lists all ClusterOperatorProgressInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*updatev1alpha1.ClusterOperatorProgressInsight, err error)
	// Get retrieves the ClusterOperatorProgressInsight from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*updatev1alpha1.ClusterOperatorProgressInsight, error)
	ClusterOperatorProgressInsightListerExpansion
}

// clusterOperatorProgressInsightLister implements the ClusterOperatorProgressInsightLister interface.
type clusterOperatorProgressInsightLister struct {
	listers.ResourceIndexer[*updatev1alpha1.ClusterOperatorProgressInsight]
}

// NewClusterOperatorProgressInsightLister returns a new ClusterOperatorProgressInsightLister.
func NewClusterOperatorProgressInsightLister(indexer cache.Indexer) ClusterOperatorProgressInsightLister {
	return &clusterOperatorProgressInsightLister{listers.New[*updatev1alpha1.ClusterOperatorProgressInsight](indexer, updatev1alpha1.Resource("clusteroperatorprogressinsight"))}
}
