// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterVersionProgressInsightLister helps list ClusterVersionProgressInsights.
// All objects returned here must be treated as read-only.
type ClusterVersionProgressInsightLister interface {
	// List lists all ClusterVersionProgressInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*updatev1alpha1.ClusterVersionProgressInsight, err error)
	// Get retrieves the ClusterVersionProgressInsight from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*updatev1alpha1.ClusterVersionProgressInsight, error)
	ClusterVersionProgressInsightListerExpansion
}

// clusterVersionProgressInsightLister implements the ClusterVersionProgressInsightLister interface.
type clusterVersionProgressInsightLister struct {
	listers.ResourceIndexer[*updatev1alpha1.ClusterVersionProgressInsight]
}

// NewClusterVersionProgressInsightLister returns a new ClusterVersionProgressInsightLister.
func NewClusterVersionProgressInsightLister(indexer cache.Indexer) ClusterVersionProgressInsightLister {
	return &clusterVersionProgressInsightLister{listers.New[*updatev1alpha1.ClusterVersionProgressInsight](indexer, updatev1alpha1.Resource("clusterversionprogressinsight"))}
}
