// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterOperatorProgressInsightListerExpansion allows custom methods to be added to
// ClusterOperatorProgressInsightLister.
type ClusterOperatorProgressInsightListerExpansion interface{}

// ClusterVersionProgressInsightListerExpansion allows custom methods to be added to
// ClusterVersionProgressInsightLister.
type ClusterVersionProgressInsightListerExpansion interface{}

// HealthInsightListerExpansion allows custom methods to be added to
// HealthInsightLister.
type HealthInsightListerExpansion interface{}

// MachineConfigPoolProgressInsightListerExpansion allows custom methods to be added to
// MachineConfigPoolProgressInsightLister.
type MachineConfigPoolProgressInsightListerExpansion interface{}

// NodeProgressInsightListerExpansion allows custom methods to be added to
// NodeProgressInsightLister.
type NodeProgressInsightListerExpansion interface{}
