// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MachineConfigPoolProgressInsightLister helps list MachineConfigPoolProgressInsights.
// All objects returned here must be treated as read-only.
type MachineConfigPoolProgressInsightLister interface {
	// List lists all MachineConfigPoolProgressInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*updatev1alpha1.MachineConfigPoolProgressInsight, err error)
	// Get retrieves the MachineConfigPoolProgressInsight from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*updatev1alpha1.MachineConfigPoolProgressInsight, error)
	MachineConfigPoolProgressInsightListerExpansion
}

// machineConfigPoolProgressInsightLister implements the MachineConfigPoolProgressInsightLister interface.
type machineConfigPoolProgressInsightLister struct {
	listers.ResourceIndexer[*updatev1alpha1.MachineConfigPoolProgressInsight]
}

// NewMachineConfigPoolProgressInsightLister returns a new MachineConfigPoolProgressInsightLister.
func NewMachineConfigPoolProgressInsightLister(indexer cache.Indexer) MachineConfigPoolProgressInsightLister {
	return &machineConfigPoolProgressInsightLister{listers.New[*updatev1alpha1.MachineConfigPoolProgressInsight](indexer, updatev1alpha1.Resource("machineconfigpoolprogressinsight"))}
}
