// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	updatev1alpha1 "github.com/openshift/api/update/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NodeProgressInsightLister helps list NodeProgressInsights.
// All objects returned here must be treated as read-only.
type NodeProgressInsightLister interface {
	// List lists all NodeProgressInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*updatev1alpha1.NodeProgressInsight, err error)
	// Get retrieves the NodeProgressInsight from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*updatev1alpha1.NodeProgressInsight, error)
	NodeProgressInsightListerExpansion
}

// nodeProgressInsightLister implements the NodeProgressInsightLister interface.
type nodeProgressInsightLister struct {
	listers.ResourceIndexer[*updatev1alpha1.NodeProgressInsight]
}

// NewNodeProgressInsightLister returns a new NodeProgressInsightLister.
func NewNodeProgressInsightLister(indexer cache.Indexer) NodeProgressInsightLister {
	return &nodeProgressInsightLister{listers.New[*updatev1alpha1.NodeProgressInsight](indexer, updatev1alpha1.Resource("nodeprogressinsight"))}
}
