// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	fmt "fmt"
	sync "sync"

	typed "sigs.k8s.io/structured-merge-diff/v4/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsight
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsightSpec
      default: {}
    - name: status
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsightStatus
      default: {}
- name: com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsightSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.openshift.api.update.v1alpha1.ClusterOperatorProgressInsightStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.ClusterVersionProgressInsight
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ClusterVersionProgressInsightSpec
      default: {}
    - name: status
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ClusterVersionProgressInsightStatus
      default: {}
- name: com.github.openshift.api.update.v1alpha1.ClusterVersionProgressInsightSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.openshift.api.update.v1alpha1.ClusterVersionProgressInsightStatus
  map:
    fields:
    - name: assessment
      type:
        scalar: string
      default: ""
    - name: completedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: completionPercent
      type:
        scalar: numeric
      default: 0
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: estimatedCompletedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: name
      type:
        scalar: string
      default: ""
    - name: startedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: versions
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ControlPlaneUpdateVersions
      default: {}
- name: com.github.openshift.api.update.v1alpha1.ControlPlaneUpdateVersions
  map:
    fields:
    - name: previous
      type:
        namedType: com.github.openshift.api.update.v1alpha1.Version
    - name: target
      type:
        namedType: com.github.openshift.api.update.v1alpha1.Version
      default: {}
- name: com.github.openshift.api.update.v1alpha1.HealthInsight
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.openshift.api.update.v1alpha1.HealthInsightSpec
      default: {}
    - name: status
      type:
        namedType: com.github.openshift.api.update.v1alpha1.HealthInsightStatus
      default: {}
- name: com.github.openshift.api.update.v1alpha1.HealthInsightSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.openshift.api.update.v1alpha1.HealthInsightStatus
  map:
    fields:
    - name: impact
      type:
        namedType: com.github.openshift.api.update.v1alpha1.InsightImpact
      default: {}
    - name: remediation
      type:
        namedType: com.github.openshift.api.update.v1alpha1.InsightRemediation
      default: {}
    - name: scope
      type:
        namedType: com.github.openshift.api.update.v1alpha1.InsightScope
      default: {}
    - name: startedAt
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: com.github.openshift.api.update.v1alpha1.InsightImpact
  map:
    fields:
    - name: description
      type:
        scalar: string
    - name: level
      type:
        scalar: string
      default: ""
    - name: summary
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.InsightRemediation
  map:
    fields:
    - name: estimatedFinish
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: reference
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.InsightScope
  map:
    fields:
    - name: resources
      type:
        list:
          elementType:
            namedType: com.github.openshift.api.update.v1alpha1.ResourceRef
          elementRelationship: atomic
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.MachineConfigPoolProgressInsight
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.openshift.api.update.v1alpha1.MachineConfigPoolProgressInsightSpec
      default: {}
    - name: status
      type:
        namedType: com.github.openshift.api.update.v1alpha1.MachineConfigPoolProgressInsightStatus
      default: {}
- name: com.github.openshift.api.update.v1alpha1.MachineConfigPoolProgressInsightSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.openshift.api.update.v1alpha1.MachineConfigPoolProgressInsightStatus
  map:
    fields:
    - name: assessment
      type:
        scalar: string
      default: ""
    - name: completionPercent
      type:
        scalar: numeric
      default: 0
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: name
      type:
        scalar: string
      default: ""
    - name: scopeType
      type:
        scalar: string
      default: ""
    - name: summaries
      type:
        list:
          elementType:
            namedType: com.github.openshift.api.update.v1alpha1.NodeSummary
          elementRelationship: associative
          keys:
          - type
- name: com.github.openshift.api.update.v1alpha1.NodeProgressInsight
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.openshift.api.update.v1alpha1.NodeProgressInsightSpec
      default: {}
    - name: status
      type:
        namedType: com.github.openshift.api.update.v1alpha1.NodeProgressInsightStatus
      default: {}
- name: com.github.openshift.api.update.v1alpha1.NodeProgressInsightSpec
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.openshift.api.update.v1alpha1.NodeProgressInsightStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
          elementRelationship: associative
          keys:
          - type
    - name: estimatedToComplete
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
    - name: message
      type:
        scalar: string
    - name: name
      type:
        scalar: string
      default: ""
    - name: poolResource
      type:
        namedType: com.github.openshift.api.update.v1alpha1.ResourceRef
      default: {}
    - name: scopeType
      type:
        scalar: string
      default: ""
    - name: version
      type:
        scalar: string
- name: com.github.openshift.api.update.v1alpha1.NodeSummary
  map:
    fields:
    - name: count
      type:
        scalar: numeric
      default: 0
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.ResourceRef
  map:
    fields:
    - name: group
      type:
        scalar: string
    - name: name
      type:
        scalar: string
      default: ""
    - name: namespace
      type:
        scalar: string
    - name: resource
      type:
        scalar: string
      default: ""
- name: com.github.openshift.api.update.v1alpha1.Version
  map:
    fields:
    - name: metadata
      type:
        list:
          elementType:
            namedType: com.github.openshift.api.update.v1alpha1.VersionMetadata
          elementRelationship: associative
          keys:
          - key
    - name: version
      type:
        scalar: string
- name: com.github.openshift.api.update.v1alpha1.VersionMetadata
  map:
    fields:
    - name: key
      type:
        scalar: string
      default: ""
    - name: value
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Condition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Duration
  scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        scalar: string
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: ""
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
